# Generated by Django 3.0.4 on 2020-03-30 17:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RationAllocated',
            fields=[
                ('cnic', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='CNIC can only be 13 digit number', regex='^[\\d]{13}$')])),
                ('org_name', models.CharField(blank=True, default='', max_length=150)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
