# Generated by Django 3.0.4 on 2020-04-09 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_auto_20200330_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationallocation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 12, 31, 39, 697270, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationallocation',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 12, 31, 55, 361681, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
