# Generated by Django 3.0.4 on 2020-04-11 04:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_auto_20200409_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('cnic', models.CharField(max_length=13, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='CNIC can only be 13 digit number', regex='^[\\d]{13}$')])),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('family_count', models.PositiveSmallIntegerField(blank=True, default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='rationallocation',
            name='cnic',
        ),
        migrations.AddField(
            model_name='rationallocation',
            name='allocation_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rationallocation',
            name='id',
            field=models.BigIntegerField(default=9999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rationallocation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ration.Person'),
        ),
    ]
