# Generated by Django 3.0.4 on 2020-04-11 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_auto_20200411_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationallocation',
            name='allocation_expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 17, 22, 9, 90552, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rationallocation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ration.Person'),
        ),
    ]
